// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxDxo3vgMXiyQR67gJYJOHihM4deV1KMg',
    appId: '1:172831835838:web:97967110edf1720afb80ef',
    messagingSenderId: '172831835838',
    projectId: 'fir-project-21b34',
    authDomain: 'fir-project-21b34.firebaseapp.com',
    storageBucket: 'fir-project-21b34.firebasestorage.app',
    measurementId: 'G-F72MJQJ19N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQT6gaLjxDlq-mlQN5tW1QuuTpjNxSXlY',
    appId: '1:172831835838:android:bbc17fd7ee828b41fb80ef',
    messagingSenderId: '172831835838',
    projectId: 'fir-project-21b34',
    storageBucket: 'fir-project-21b34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1kTBS9PvKqt_zlcdbgulyXAb7MvqQIK0',
    appId: '1:172831835838:ios:8cb70bd1b3d44520fb80ef',
    messagingSenderId: '172831835838',
    projectId: 'fir-project-21b34',
    storageBucket: 'fir-project-21b34.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1kTBS9PvKqt_zlcdbgulyXAb7MvqQIK0',
    appId: '1:172831835838:ios:8cb70bd1b3d44520fb80ef',
    messagingSenderId: '172831835838',
    projectId: 'fir-project-21b34',
    storageBucket: 'fir-project-21b34.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxDxo3vgMXiyQR67gJYJOHihM4deV1KMg',
    appId: '1:172831835838:web:4cbcb8b553e1d3d3fb80ef',
    messagingSenderId: '172831835838',
    projectId: 'fir-project-21b34',
    authDomain: 'fir-project-21b34.firebaseapp.com',
    storageBucket: 'fir-project-21b34.firebasestorage.app',
    measurementId: 'G-J4G747B3KB',
  );
}
